# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_auto_20160915_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/imagens'),
        ),
        migrations.AlterField(
            model_name='post',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/imagens/thumbnail'),
        ),
    ]
