# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_auto_20160915_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='miniatura',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
