# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_auto_20160915_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='noticia/thumbnail'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticia'),
        ),
    ]
