# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0007_auto_20160920_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
