# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0009_remove_post_miniatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Secundaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_secundario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.Post')),
            ],
        ),
    ]
