# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0010_principal_secundaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
