# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0013_auto_20161018_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secundaria',
            name='post_secundario',
        ),
        migrations.DeleteModel(
            name='Secundaria',
        ),
    ]
