# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0014_auto_20161025_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name': 'Principal', 'verbose_name_plural': 'Principais'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topico',
            field=models.CharField(blank=True, choices=[('professor', 'Professor'), ('tecnico', 'Técnico Administrativo'), ('concurso', 'Concurso do Departamento de Engenharia de Transportes e Geodésia'), ('monitoria', 'Monitoria'), ('estagio', 'Estágio'), ('viagem', 'Viagem para atividades acadêmica'), ('congresso', 'Congresso'), ('seminario', 'Seminário'), ('simposio', 'Simpósio'), ('artigo', 'Artigo')], max_length=200, null=True),
        ),
    ]
