# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0015_auto_20161122_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topico',
            field=models.CharField(blank=True, choices=[('concurso', 'Concurso do Departamento de Engenharia de Transportes e Geodésia'), ('monitoria', 'Monitoria'), ('estagio', 'Estágio'), ('viagem', 'Viagem para atividades acadêmica'), ('congresso', 'Congresso'), ('seminario', 'Seminário'), ('simposio', 'Simpósio'), ('artigo', 'Artigo')], max_length=200, null=True),
        ),
    ]
