# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0016_auto_20161209_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='post_principal',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
