# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161003_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='core/documentos')),
            ],
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='arquivo',
            field=models.FileField(upload_to='core/disciplinas'),
        ),
    ]
