# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publicacao_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Atalho'),
        ),
    ]
