# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161018_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='slug',
            field=models.SlugField(),
        ),
    ]
