# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161018_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='slug',
        ),
        migrations.AddField(
            model_name='bolsista',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='tecnico_adm',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
