# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161018_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='tecnico_adm',
            name='slug',
            field=models.SlugField(),
        ),
    ]
