# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161018_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='horario_de_atendimento',
        ),
    ]
