# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_funcionario_horario_de_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='horario_de_atendimento',
            field=models.DateTimeField(null=True),
        ),
    ]
