# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_funcionario_horario_de_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='horario_de_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
