# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_funcionario_horario_de_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='horario_de_atendimento',
        ),
    ]
