# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_funcionario_horario_de_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='horario_de_atendimento',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ano',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='core/disciplinas'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Disciplinas',
        ),
    ]
