# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20161020_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico_adm',
            name='matricula',
        ),
        migrations.DeleteModel(
            name='Tecnico_adm',
        ),
    ]
