# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20161020_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico_adm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Funcionario')),
            ],
        ),
    ]
