# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20161024_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labarotorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=70)),
                ('imagens', models.ImageField(blank=True, null=True, upload_to='core/laboratorio')),
                ('descricao', models.TextField(max_length=700)),
                ('hardware', models.TextField(blank=True, max_length=300, null=True)),
                ('software', models.TextField(blank=True, max_length=300, null=True)),
                ('agenda', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
