# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_labarotorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labarotorio',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='link',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='agenda',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='hardware',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='core/laboratorio'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='software',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='descricao',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
