# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20161209_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='descricao',
            field=models.TextField(),
        ),
    ]
