# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20161209_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='core/documentos')),
            ],
        ),
    ]
