# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especializacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=70)),
                ('imagens', models.ImageField(blank=True, null=True, upload_to='core/especializacao')),
                ('titulo1', models.CharField(max_length=150)),
                ('descricao1', models.TextField()),
                ('titulo2', models.CharField(max_length=150)),
                ('descricao2', models.TextField()),
                ('titulo3', models.CharField(max_length=150)),
                ('descricao3', models.TextField()),
                ('titulo4', models.CharField(max_length=150)),
                ('descricao4', models.TextField()),
                ('titulo5', models.CharField(max_length=150)),
                ('descricao5', models.TextField()),
                ('titulo6', models.CharField(max_length=150)),
                ('descricao6', models.TextField()),
                ('titulo7', models.CharField(max_length=150)),
                ('descricao7', models.TextField()),
                ('titulo8', models.CharField(max_length=150)),
                ('descricao8', models.TextField()),
                ('titulo9', models.CharField(max_length=150)),
                ('descricao9', models.TextField()),
            ],
        ),
    ]
