# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_especializacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especializacao',
            name='descricao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='descricao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='descricao3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='descricao4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='descricao5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='descricao6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='descricao7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='descricao8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='descricao9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='titulo2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='titulo3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='titulo4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='titulo5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='titulo6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='titulo7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='titulo8',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='especializacao',
            name='titulo9',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
