# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170313_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especializacao',
            name='imagens',
        ),
    ]
