# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20170313_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especializacao',
            name='descricao9',
        ),
        migrations.AddField(
            model_name='especializacao',
            name='item93',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='especializacao',
            name='item94',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='especializacao',
            name='item95',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
