# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20170313_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='especializacao',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='core/especializacao'),
        ),
    ]
